### ISSUE TITLE
Consider wrapping views with explicit transaction.atomic decorator

### ISSUE THREAD

**Issue by marcinn** [django-getpaid/django-getpaid#110]
This app plays with cash, but most of all of getpaid views aren't wrapped with atomic() and default Django behaviour is an autocommit. This setup results in unfinished processing when some error occurs (i.e. cant connect to smtp). 

Why explicit atomics? Most of project views may be leaved in autocommit mode (due to performance, for example), so ATOMIC_REQUESTS may be not enabled, and  Getpaid should use transactions in such cases.

I know that decorating CBVs is a nightmare. May advice - do not use CBVs. CBVs are bad. Cheers! :beer:

**Comment by dekoza** [comment]
No longer relevant after 2.0 release. Crucial methods are now decorated with `@atomic`

**Comment by marcinn** [comment]
Thanks.
