### ISSUE TITLE
Invalid import in dotpay backend

### ISSUE THREAD

**Issue by a-olszewski** [django-getpaid/django-getpaid#132]
https://github.com/django-getpaid/django-getpaid/blob/97cd5c185da2c679469985db304f89d6ac977e84/getpaid/backends/dotpay/urls.py#L3

`ImportError: cannot import name 'ReturnView'`

Should be from getpaid.backends.dotpay.**views** import OnlineView, ReturnView

**Comment by dekoza** [comment]
No longer relevant after 2.0 release. Versions 1.x are no longer supported.
