### ISSUE TITLE
Setting `unique=True` on Payment model throws a warning

### ISSUE THREAD

**Issue by andreyshipilov** [django-getpaid/django-getpaid#135]
* django-getpaid version: 1.8.0.1
* Django version: 2.1.7
* Python version: 3.3
* Operating System: macOS X Mojave / Docker

### Description

In the docs [you describe how to make multiple payments per order](https://django-getpaid.readthedocs.io/en/latest/workflow.html#getpaid.register_to_payment). I need to implement a single payment per order. Hence in the Order model registration I use `getpaid.register_to_payment(Order, unique=True, related_name='payments')`

This throws a warning in the logs/console:
```
WARNINGS:
getpaid.Payment.order: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
```
And this breaks the build in our environment.

Am I doing the single payment per order in a wrong way or am I missing something?

Here's the whole Order model definition:
```
from django.urls import reverse
from django.db import models
import getpaid


class Order(models.Model):
    STATUS_CHOICES = (
        ('W', 'Waiting for payment'),
        ('P', 'Payment complete')
    )

    amount = models.DecimalField(decimal_places=2, max_digits=8, default=0)
    currency = models.CharField(max_length=3, default='USD')
    status = models.CharField(max_length=1, blank=True, default='W', choices=STATUS_CHOICES)
    transaction_id = models.CharField(max_length=16)

    def get_absolute_url(self):
        return reverse('order_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.transaction_id


getpaid.register_to_payment(Order, unique=True, related_name='payments')

```

**Comment by dekoza** [comment]
No longer relevant after 2.0 release. Versions 1.x are no longer supported.
