### ISSUE TITLE
Please update to Django 3.1

### ISSUE THREAD

**Issue by NotJustPizza** [django-getpaid/django-getpaid#148]
* django-getpaid version: 2.2.1
* Django version: 3.1
* Python version: 3.7.3
* Operating System: Linux

### Description

Partial error log:
```
  File "/venv/lib/python3.7/site-packages/getpaid/__init__.py", line 1, in <module>
    from .types import FraudStatus, PaymentStatus
  File "/venv/lib/python3.7/site-packages/getpaid/types.py", line 6, in <module>
    from django.utils.decorators import classproperty
ImportError: cannot import name 'classproperty' from 'django.utils.decorators' 
```

Issue reason:
`django.utils.decorators.classproperty() decorator is made public and moved to django.utils.functional.classproperty().` (https://docs.djangoproject.com/en/3.1/releases/3.1/#id1)

### What I Did

```
python3 manage.py test 
```

**Comment by NotJustPizza** [comment]
https://github.com/django-getpaid/django-getpaid/pull/149

**Comment by onufrienkovi** [comment]
> #149
Your changes will result in errors for Django < 3.1.
Consider compatibility with previous versions #150
