### ISSUE TITLE
Moip subscription backend

### ISSUE THREAD

**Issue by henriquebastos** [django-getpaid/django-getpaid#39]
Moip created a subscription feature as a [new separated API](http://moiplabs.github.io/assinaturas-docs/api.html).

I'm working on a python library to abstract the API and wish to add support for it in getpaid.

Since it's a completely different API, with it's own settings, I'm thinking about creating a new backend for it.

Do you have any opinions on that?

**Comment by pawciobiel** [comment]
@henriquebastos IMHO it may be a better option to create a new app `django-getpaid-subscriptions` that adds subscription features there. I was actually thinking about adding similar functionality for one of the backends this way. I don't think it would be good to mix in subscriptions with payment processors.

**Comment by pawciobiel** [comment]
@cypreess do you have any thoughts on this one?

**Comment by cypreess** [comment]
Subscription model is totally different from what getpaid was designed for.

I think - if we go this path and add subscriptions to getpaid - we need definitely redesign the architecture of getpaid. Just a few things that comes to my mind:
1) new payment form/view - should support apart from one-time payments, also subscription in some way. Not trivial task - what if somebody want to enable only onetime or only subscription for certain type of orders?
2) some triggering when automatic payment is done - usually you would like to issue some order/invoice in the application 
3) refunds policy - the very usual thing with automatics charging CredtitCards is someone issue a refund, I don't think getpaid right now deals with refund in any way.
4) Change in every backend we support - as API of backend will definitelly change (maybe we could introduce backwards compatible change by adding some methods, if they are not present, backend does not provide subscriptions..)

Generally speaking - from one hand I think a subscription model is  a legitimate way for accepting payments in many use case and we could support it, from the second hand, maybe the subscription model is so specific that the stand alone app for that is better choice. 

The only argument pros the integration of both, is to support business models which benefit from both one-time and subscription payments at the same time. Maybe it is worth the effort.

**Comment by dekoza** [comment]
No longer relevant after 2.0 release. Versions 1.x are no longer supported. Plus, this Issue has been neglected for too long. If anyone feels this is still relevant after nearly 5 years, please reopen.
